name: clang-format

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt install clang-format
        clang-format --version

    - name: Run tests
      run: |
        ./clang_validate.sh
