name: clang-format check

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path:
          - 'code/src'
          - 'code/include'
          - 'code/tests'

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.9.0
      with:
        clang-format-version: '14'
        check-path: ${{ matrix.path }}
